all:
	gcc -o exercicio1 exercicio1.c stack.c
	gcc -o maze maze.c pstack.c
	gcc -o parser parser.c stack.c
	gcc -o polish polish.c stack.c
	gcc -o reverse reverse.c stack.c queue.c
	gcc -o minesweeper minesweeper.c pstack.c
clean:
	rm maze parser polish reverse minesweeper

